language: cpp


matrix:
  include:
    - name: "Linux - Clang"
      os: linux
      env: CXX_EXE=/usr/bin/clang++-10 CC_EXE=/usr/bin/clang-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3-pip
            - clang-10
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
            - libxrandr-dev


install:
  - pip install conan cmake
  - conan user


script:
  - conan --version
  - cmake --version
  - mkdir build
  - cd build
  - conan install .. -s build_type=Debug -s compiler.runtime=MDd --build missing
  - cmake ..
  - cmake --build . -- -j8
  - cd tests
  - ctest