language: cpp
compiler: clang
os: windows

install:
  - pip install conan cmake

script:
  - conan --version
  - cmake --version
  - mkdir build
  - cd build
  - conan install .. -s build_type=Debug -s compiler.runtime=MDd --build missing
  - cmake ..
  - cmake --build . -- -j8
  - cd tests
  - ctest