matrix:
  include:
    # linux focal build
    - name: "Linux - Clang - Ubuntu 20.04 LTS"
      language: cpp
      os: linux
      dist: focal
      env:
        - CXX_EXE=/usr/bin/clang++-10
        - CC_EXE=/usr/bin/clang-10
        - CXX=/usr/bin/clang++-10
        - CC=/usr/bin/clang-10
        - CONAN_SYSREQUIRES_MODE=enabled
      cache:
        directories:
          - $HOME/.conan/data
      addons:
        apt:
          packages:
            - python3-pip
            - clang-10
            - libstdc++-10-dev
            - libc++abi-10-dev
            - ninja-build
            - libgl1-mesa-dev

      install:
        - pip3 install conan cmake
        - conan user

      script:
        - conan --version
        - cmake --version
        - conan create . -s compiler=clang -s compiler.version=10 -s build_type=Release --build=missing

#     # windows build
#     - name: "Windows - MSVC"
#       language: python
#       os: windows
#       arch: amd64
#       
#       cache:
#         directories:
#           - "%HOMEDRIVE%%HOMEPATH%/.conan/data"
# 
#       install:
#         - pip install conan cmake ninja
#         - RefreshEnv.cmd
# 
#       script:
#         - conan --version
#         - cmake --version
#         - mkdir build && cd build
#         - conan install .. -s compiler.runtime=MDd -s build_type=Debug --build missing
#         - cmake .. -GNinja
#         - cmake --build .
#         - cd tests
#         - ctest