language: cpp


matrix:
  include:
    - name: "Linux - Clang - Ubuntu 20.04 LTS"
      os: linux
      dist: focal
      arch: amd64
      env: CXX_EXE=/usr/bin/clang++-10 CC_EXE=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10
      cache:
        directories:
          - $HOME/.conan/data
      addons:
        apt:
          packages:
            - python3-pip
            - clang-10
            - ninja-build
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - libxcb1-dev
            - libx11-xcb-dev
            - libxcb-render-util0-dev
            - libxcb-xkb-dev
            - libxcb-icccm4-dev
            - libxcb-image0-dev
            - libxcb-keysyms1-dev


install:
  - pip install conan cmake
  - conan user


script:
  - conan --version
  - cmake --version
  - mkdir build
  - cd build
  - conan install .. -s compiler=clang -s compiler.version=10 -s build_type=Debug --build missing
  - cmake .. -GNinja
  - cmake --build .
  - cd tests
  - ctest