language: cpp


matrix:
  include:
    # linux focal build
    - name: "Linux - Clang - Ubuntu 20.04 LTS"
      os: linux
      dist: focal
      arch: amd64
      env: CXX_EXE=/usr/bin/clang++-10 CC_EXE=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10
      cache:
        directories:
          - $HOME/.conan/data
      addons:
        apt:
          packages:
            - python3-pip
            - clang-10
            - libstdc++-10-dev
            - libc++abi-10-dev
            - ninja-build
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - libx11-xcb-dev
            - libxcb1-dev
            - libxcb-render-util0-dev
            - libxcb-randr0-dev
            - libxcb-icccm4-dev
            - libxcb-image0-dev
            - libxcb-keysyms1-dev
            - libxcb-shape0-dev
            - libxcb-sync-dev
            - libxcb-util0-dev
            - libxcb-xfixes0-dev
            - libxcb-xinerama0-dev
            - libxcb-xinput-dev
            - libxcb-xkb-dev
            - libxcb-xrm-dev
            - libxcb-xtest0-dev
            - libxcb-xv0-dev
            - libxcb-xvmc0-dev

      install:
        - pip install conan cmake
        - conan user

      script:
        - conan --version
        - cmake --version
        - mkdir build && cd build
        - conan install .. -s compiler=clang -s compiler.version=10 -s build_type=Debug --build missing
        - cmake .. -GNinja
        - cmake --build .
        - cd tests
        - ctest

    # windows build
    - name: "Windows - MSVC"
      os: windows
      arch: amd64
      
      cache:
        directories:
          - "%HOMEDRIVE%%HOMEPATH%/.conan/data"

      install:
        - choco install python ninja --params="'/AddToPath:1'"

      script:
        - RefreshEnv.cmd
        - conan --version
        - cmake --version
        - mkdir build && cd build
        - conan install .. -s compiler.runtime=MDd -s build_type=Debug --build missing
        - cmake .. -GNinja
        - cmake --build .
        - cd tests
        - ctest