language: cpp


matrix:
  include:
    - name: "Linux - Clang - Ubuntu 20.04 LTS"
      os: linux
      dist: focal
      arch: amd64
      env: CXX_EXE=/usr/bin/clang++ CC_EXE=/usr/bin/clang
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3-pip
            - clang
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
            - libxrandr-dev


install:
  - pip install conan cmake
  - conan user


script:
  - conan --version
  - cmake --version
  - mkdir build
  - cd build
  - conan install .. -s compiler=clang -s compiler.version=10 -s build_type=Debug --build missing
  - cmake ..
  - cmake --build . -- -j8
  - cd tests
  - ctest