name: CMake

on: [push, workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup OpenGL
      uses: openrndr/setup-opengl@v1
    
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v3.3
      with:
        setupOnly: true
        vcpkgDirectory: '${{runner.workspace}}/vcpkg'
        vcpkgGitCommitId: 4a08a10
    - run: |
        ${{runner.workspace}}/vcpkg/vcpkg install openal-soft glfw3 glad box2d miniz enet freetype ms-gsl entt spdlog fmt stb minimp3 glm

    
    - name: 'Build with CMake and Ninja'
      uses: lukka/run-cmake@v2
      with:
        useVcpkgToolchainFile: true
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ github.workspace }}/build'
        cmakeAppendedArgs: ''
